import { ArrowRight, ChevronDown, Clock3, Mail, MapPin, Phone, Route } from "lucide-react";
import ContactForm from "@/components/contact/ContactForm";
import Container from "@/components/ui/Container";
import { siteGegevens } from "@/components/layout/Footer";
import { whatsappLink } from "@/lib/utils";

const hours = [["Maandag - vrijdag", "09:00 - 18:00"], ["Zaterdag", "09:00 - 16:00"], ["Zondag", "Gesloten"]];
const faqs = [
  ["Wanneer kan ik een proefrit maken?", "Een proefrit kan tijdens onze openingsuren. We raden aan om vooraf even contact op te nemen, zodat we de wagen voor je klaar kunnen zetten."],
  ["Moet ik vooraf een afspraak maken?", "Dat hoeft niet, maar een afspraak helpt ons om je gericht en zonder wachttijd verder te helpen."],
  ["Kan ik mijn huidige wagen inruilen?", "Ja, we bekijken graag de mogelijkheden. Bezorg ons alvast de gegevens van je wagen of kom langs voor een waardebepaling."],
  ["Hoe snel krijg ik antwoord?", "We beantwoorden berichten zo snel mogelijk en streven ernaar om binnen een werkdag te reageren."],
  ["Kan ik buiten de openingsuren langskomen?", "Dat kan op afspraak. Neem even contact op, dan zoeken we samen een geschikt moment."],
];

function ContactDetail({ icon: Icon, label, children, href }) {
  const content = <><span className="mt-0.5 rounded-sm border border-white/10 bg-white/[0.03] p-2 text-neutral-300"><Icon size={18} strokeWidth={1.6} /></span><span><span className="block text-xs uppercase tracking-[0.16em] text-neutral-500">{label}</span><span className="mt-1 block text-sm text-neutral-200 transition group-hover:text-white">{children}</span></span></>;
  return href ? <a href={href} className="group flex gap-4 rounded-sm py-2 outline-none transition hover:bg-white/[0.03] focus-visible:ring-2 focus-visible:ring-white/70">{content}</a> : <div className="flex gap-4 py-2">{content}</div>;
}

export default function Page() {
  const phoneHref = `tel:${siteGegevens.phoneNumber.replaceAll(" ", "")}`;
  return <>
    <section className="border-b border-white/10 bg-neutral-950"><Container className="pb-14 pt-16 lg:pb-20 lg:pt-24"><p className="text-xs font-bold tracking-[0.3em] text-red-400">CONTACT</p><h1 className="mt-5 max-w-3xl text-4xl font-black tracking-tight text-white sm:text-5xl lg:text-6xl">We helpen je graag verder</h1><p className="mt-6 max-w-2xl text-base leading-7 text-neutral-400">Heb je een vraag over een wagen, de verkoop van je auto, financiering of onze diensten? Neem contact met ons op en we antwoorden zo snel mogelijk.</p></Container></section>
    <section aria-labelledby="contact-heading"><Container className="py-16 lg:py-24"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:gap-20">
      <div className="order-2 lg:order-1"><p className="text-xs font-bold uppercase tracking-[0.2em] text-neutral-500">Contactinformatie</p><h2 id="contact-heading" className="mt-3 text-2xl font-bold">Neem contact met ons op</h2><p className="mt-4 max-w-md text-sm leading-6 text-neutral-400">Persoonlijk advies over een wagen, een overname of financiering? Ons team denkt graag met je mee.</p><div className="mt-8 space-y-3"><ContactDetail icon={Phone} label="Telefoon" href={phoneHref}>{siteGegevens.phoneNumber}</ContactDetail><ContactDetail icon={Mail} label="E-mail" href={`mailto:${siteGegevens.email}`}>{siteGegevens.email}</ContactDetail><ContactDetail icon={MapPin} label="Adres">{siteGegevens.address}</ContactDetail></div><div className="mt-8 flex flex-wrap gap-3"><a href={phoneHref} className="inline-flex min-h-11 items-center gap-2 rounded-sm bg-white px-5 text-sm font-bold text-neutral-950 transition hover:bg-neutral-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white"><Phone size={16} />Bel ons</a><a href={whatsappLink("Hallo NEM Motors, ik heb een vraag.")} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded-sm border border-white/15 px-5 text-sm font-bold text-white transition hover:border-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white"><span aria-hidden="true">WA</span>WhatsApp</a></div></div>
      <div className="order-1 rounded-sm border border-white/10 bg-neutral-900/70 p-6 sm:p-8 lg:order-2"><p className="text-xs font-bold uppercase tracking-[0.2em] text-neutral-500">Bericht sturen</p><h2 className="mt-3 text-2xl font-bold">Stuur ons een bericht</h2><ContactForm /></div>
    </div></Container></section>
    <section className="border-y border-white/10 bg-neutral-900/40" aria-labelledby="location-heading"><Container className="py-16 lg:py-24"><div className="grid gap-6 lg:grid-cols-[1.25fr_0.75fr]"><div className="flex min-h-[360px] items-center justify-center rounded-sm border border-white/10 bg-[linear-gradient(135deg,rgba(255,255,255,0.04)_25%,transparent_25%,transparent_50%,rgba(255,255,255,0.04)_50%,rgba(255,255,255,0.04)_75%,transparent_75%)] bg-[length:28px_28px] p-8 text-center"><div><MapPin className="mx-auto text-red-400" size={30} strokeWidth={1.5} /><p className="mt-4 font-semibold text-white">Onze showroom</p><p className="mt-2 text-sm text-neutral-500">{siteGegevens.address}</p><p className="mt-5 text-xs uppercase tracking-[0.16em] text-neutral-600">Google Maps-placeholder</p></div></div><div className="rounded-sm border border-white/10 bg-neutral-950 p-6 sm:p-8"><Clock3 className="text-neutral-400" size={22} strokeWidth={1.5} /><h2 id="location-heading" className="mt-5 text-2xl font-bold">Bezoek onze showroom</h2><p className="mt-4 flex gap-3 text-sm leading-6 text-neutral-400"><MapPin className="mt-1 shrink-0" size={17} />{siteGegevens.address}</p><dl className="mt-7 space-y-3 border-t border-white/10 pt-6 text-sm">{hours.map(([day, time]) => <div key={day} className="flex justify-between gap-4"><dt className="text-neutral-500">{day}</dt><dd className={time === "Gesloten" ? "text-neutral-500" : "text-neutral-200"}>{time}</dd></div>)}</dl><a href="https://www.google.com/maps/search/?api=1&query=Ambachtslaan+5%2F10%2C+3665+As" target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-white transition hover:text-red-400 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white"><Route size={17} />Route plannen<ArrowRight size={16} /></a></div></div></Container></section>
    <section aria-labelledby="faq-heading"><Container className="max-w-4xl py-16 lg:py-24"><p className="text-xs font-bold uppercase tracking-[0.2em] text-neutral-500">Veelgestelde vragen</p><h2 id="faq-heading" className="mt-3 text-2xl font-bold">Goed om te weten</h2><div className="mt-8 border-t border-white/10">{faqs.map(([question, answer]) => <details key={question} className="group border-b border-white/10"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 py-5 text-sm font-semibold text-neutral-200 outline-none transition hover:text-white focus-visible:ring-2 focus-visible:ring-white"><span>{question}</span><ChevronDown size={18} className="shrink-0 text-neutral-500 transition group-open:rotate-180" /></summary><p className="max-w-2xl pb-5 pr-8 text-sm leading-6 text-neutral-400">{answer}</p></details>)}</div></Container></section>
    <section className="border-t border-white/10 bg-neutral-900/50"><Container className="flex flex-col gap-6 py-12 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-2xl font-bold">Liever meteen contact?</h2><p className="mt-2 text-sm text-neutral-400">Ons team staat klaar om je verder te helpen.</p></div><div className="flex flex-wrap gap-3"><a href={phoneHref} className="inline-flex min-h-11 items-center gap-2 rounded-sm bg-white px-5 text-sm font-bold text-neutral-950 transition hover:bg-neutral-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white"><Phone size={16} />Bel ons</a><a href={`mailto:${siteGegevens.email}`} className="inline-flex min-h-11 items-center gap-2 rounded-sm border border-white/15 px-5 text-sm font-bold text-white transition hover:border-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white"><Mail size={16} />Stuur een e-mail</a></div></Container></section>
  </>;
}
