create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  user_id uuid unique references auth.users(id) on delete set null,
  email text not null unique check (email = lower(trim(email))),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.admin_users (email, active)
values ('semihozyurek25@gmail.com', true)
on conflict (email) do update set active = true, updated_at = now();

create table if not exists public.admin_login_attempts (
  key_hash text primary key,
  attempt_count integer not null default 0 check (attempt_count >= 0),
  window_started_at timestamptz not null default now(),
  blocked_until timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
alter table public.admin_users force row level security;
alter table public.admin_login_attempts enable row level security;
alter table public.admin_login_attempts force row level security;

revoke all on public.admin_users from anon, authenticated;
revoke all on public.admin_login_attempts from anon, authenticated;
