create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) > 0),
  email text not null check (email ~* '^.+@.+\..+$'),
  message text not null,
  status text not null default 'nieuw' check (status in ('nieuw', 'afgehandeld')),
  created_at timestamptz not null default now()
);

create table if not exists public.test_drive_requests (
  id bigint generated by default as identity primary key,
  vehicle_id bigint not null references public.vehicles(id) on delete cascade,
  name text not null check (char_length(trim(name)) > 0),
  email text not null check (email ~* '^.+@.+\..+$'),
  phone text not null,
  date text not null,
  time text not null,
  message text,
  status text not null default 'nieuw' check (status in ('nieuw', 'afgehandeld')),
  created_at timestamptz not null default now()
);

create table if not exists public.sell_requests (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) > 0),
  email text not null check (email ~* '^.+@.+\..+$'),
  phone text not null,
  brand text not null,
  model text not null,
  year integer not null,
  mileage integer not null,
  price numeric(12,2),
  message text,
  status text not null default 'nieuw' check (status in ('nieuw', 'afgehandeld')),
  created_at timestamptz not null default now()
);

create table if not exists public.sell_request_images (
  id bigint generated by default as identity primary key,
  sell_request_id bigint not null references public.sell_requests(id) on delete cascade,
  storage_path text not null unique,
  public_url text not null,
  created_at timestamptz not null default now()
);

-- RLS
alter table public.contact_requests enable row level security;
alter table public.test_drive_requests enable row level security;
alter table public.sell_requests enable row level security;
alter table public.sell_request_images enable row level security;

-- Only admins can read/write directly to tables. 
-- Public submission will go through a service role key in an API route, 
-- or we can enable insert for anon/authenticated if we want direct POST from client.
-- Since the plan says API routes, we will keep RLS strict.
revoke all on public.contact_requests from anon, authenticated;
revoke all on public.test_drive_requests from anon, authenticated;
revoke all on public.sell_requests from anon, authenticated;
revoke all on public.sell_request_images from anon, authenticated;

-- Storage Bucket for Sell Images
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('sell-images', 'sell-images', false, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'image/avif'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Storage Policies
-- We'll allow public to upload through signed URLs or Service Role API.
-- Because the API will use Service Role, we don't strictly need public insert policies.

