create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,
  brand text not null check (char_length(trim(brand)) between 1 and 80),
  model text not null check (char_length(trim(model)) between 1 and 120),
  title text,
  trim text,
  year integer check (year between 1900 and 2100),
  first_registration text,
  price numeric(12,2) not null default 0 check (price >= 0),
  mileage integer check (mileage >= 0),
  fuel text,
  transmission text,
  power integer check (power >= 0),
  power_kw integer check (power_kw >= 0),
  body text,
  vehicle_type text,
  drivetrain text,
  seats integer check (seats > 0),
  doors integer check (doors > 0),
  battery_capacity numeric(8,2) check (battery_capacity >= 0),
  range_km integer check (range_km >= 0),
  engine_capacity integer check (engine_capacity >= 0),
  cylinders integer check (cylinders > 0),
  emission_class text,
  co2_emission numeric(8,2) check (co2_emission >= 0),
  energy_label text,
  color text,
  paint_type text,
  interior_color text,
  upholstery text,
  service_history boolean,
  non_smoker boolean,
  description text,
  options text[] not null default '{}',
  vat_label text,
  status text not null default 'concept' check (status in ('concept', 'beschikbaar', 'gereserveerd', 'verkocht')),
  featured boolean not null default false,
  new_arrival boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vehicle_images (
  id bigint generated by default as identity primary key,
  vehicle_id bigint not null references public.vehicles(id) on delete cascade,
  storage_path text not null unique,
  public_url text not null,
  alt_text text,
  position integer not null default 0 check (position >= 0),
  created_at timestamptz not null default now()
);

create index if not exists vehicles_public_inventory_idx on public.vehicles(status, published_at desc, created_at desc);
create index if not exists vehicle_images_vehicle_position_idx on public.vehicle_images(vehicle_id, position);

create or replace function public.set_vehicle_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_vehicle_updated_at on public.vehicles;
create trigger set_vehicle_updated_at before update on public.vehicles
for each row execute function public.set_vehicle_updated_at();

alter table public.vehicles enable row level security;
alter table public.vehicle_images enable row level security;
alter table public.vehicles force row level security;
alter table public.vehicle_images force row level security;

revoke all on public.vehicles from anon, authenticated;
revoke all on public.vehicle_images from anon, authenticated;
grant select on public.vehicles to anon, authenticated;
grant select on public.vehicle_images to anon, authenticated;

drop policy if exists "Public can read published vehicles" on public.vehicles;
create policy "Public can read published vehicles"
on public.vehicles for select
to anon, authenticated
using (status in ('beschikbaar', 'gereserveerd', 'verkocht') and published_at is not null);

drop policy if exists "Public can read images of published vehicles" on public.vehicle_images;
create policy "Public can read images of published vehicles"
on public.vehicle_images for select
to anon, authenticated
using (exists (
  select 1 from public.vehicles
  where vehicles.id = vehicle_images.vehicle_id
    and vehicles.status in ('beschikbaar', 'gereserveerd', 'verkocht')
    and vehicles.published_at is not null
));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('vehicle-images', 'vehicle-images', true, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'image/avif'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can read vehicle images" on storage.objects;
create policy "Public can read vehicle images"
on storage.objects for select
to public
using (bucket_id = 'vehicle-images');
